/* ── SitePulse AI — HTML Report Export Service ── */

import type { AnalysisResult } from '@/types/analysis';

/**
 * Generate a standalone, styled HTML report from analysis results.
 */
export function generateHTMLReport(result: AnalysisResult): string {
  const recRows = result.recommendations
    .map(
      (r) => `
      <tr>
        <td class="rank">#${r.rank}</td>
        <td>
          <span class="priority priority-${r.priority.toLowerCase().replace(/[^a-z]/g, '')}">${r.priority}</span>
          <strong>${r.title}</strong>
          <p>${r.description}</p>
          <p class="fix"><strong>Fix:</strong> ${r.fix}</p>
          <pre><code>${escapeHtml(r.copyReadyExample)}</code></pre>
        </td>
      </tr>`
    )
    .join('');

  const aeoModules = result.aeo.modules
    .map(
      (m) => `
      <div class="module">
        <h3>${m.title}</h3>
        <pre>${escapeHtml(m.content)}</pre>
      </div>`
    )
    .join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SitePulse AI Report — ${escapeHtml(result.url)}</title>
  <style>
    :root { --bg: #0a0a0f; --card: #15151f; --border: #2a2a3a; --text: #e0e0e8; --muted: #9090a0; --accent: #f97316; --purple: #a78bfa; }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', system-ui, sans-serif; background: var(--bg); color: var(--text); padding: 2rem; line-height: 1.6; }
    h1 { font-size: 1.8rem; margin-bottom: 0.5rem; }
    h2 { font-size: 1.4rem; margin: 2rem 0 1rem; border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; }
    h3 { font-size: 1.1rem; margin-bottom: 0.5rem; }
    .header { text-align: center; margin-bottom: 2rem; }
    .header .url { color: var(--accent); }
    .header .badge { display: inline-block; background: #1e1e2e; border: 1px solid var(--border); border-radius: 6px; padding: 2px 10px; font-size: 0.75rem; font-weight: 700; letter-spacing: 1px; margin-left: 8px; }
    .scores { display: flex; gap: 1.5rem; justify-content: center; margin-bottom: 2rem; }
    .score-card { background: var(--card); border: 1px solid var(--border); border-radius: 12px; padding: 1.5rem 2.5rem; text-align: center; }
    .score-card .value { font-size: 2.5rem; font-weight: 800; }
    .score-card .label { color: var(--muted); font-size: 0.85rem; text-transform: uppercase; letter-spacing: 1px; }
    .seo .value { color: var(--accent); }
    .aeo .value { color: var(--purple); }
    table { width: 100%; border-collapse: collapse; }
    tr { border-bottom: 1px solid var(--border); }
    td { padding: 1rem 0.5rem; vertical-align: top; }
    .rank { font-weight: 800; font-size: 1.2rem; color: var(--accent); width: 50px; }
    .priority { display: inline-block; font-size: 0.7rem; font-weight: 700; padding: 2px 8px; border-radius: 4px; margin-bottom: 4px; text-transform: uppercase; letter-spacing: 0.5px; }
    .priority-quickwin { background: #166534; color: #4ade80; }
    .priority-highimpact { background: #7c2d12; color: #fb923c; }
    .priority-medium { background: #1e3a5f; color: #60a5fa; }
    .priority-lowpriority { background: #27272a; color: #a1a1aa; }
    .fix { color: var(--muted); font-size: 0.9rem; }
    pre { background: #0d0d14; border: 1px solid var(--border); border-radius: 6px; padding: 0.75rem; font-size: 0.8rem; overflow-x: auto; margin-top: 0.5rem; white-space: pre-wrap; }
    .module { background: var(--card); border: 1px solid var(--border); border-radius: 8px; padding: 1rem; margin-bottom: 1rem; }
    .footer { text-align: center; color: var(--muted); margin-top: 3rem; font-size: 0.8rem; }
  </style>
</head>
<body>
  <div class="header">
    <h1>◆ SitePulse AI Report</h1>
    <p>Analysis for <span class="url">${escapeHtml(result.url)}</span> <span class="badge">${result.complexity}</span></p>
    <p style="color:var(--muted);font-size:0.85rem">Generated ${result.analyzedAt}</p>
  </div>

  <div class="scores">
    <div class="score-card seo">
      <div class="value">${result.seo.score}</div>
      <div class="label">SEO Score</div>
    </div>
    <div class="score-card aeo">
      <div class="value">${result.aeo.score}</div>
      <div class="label">AEO Score</div>
    </div>
  </div>

  <h2>🎯 Top ${result.recommendations.length} Recommendations</h2>
  <table>${recRows}</table>

  <h2>🤖 AEO Content Modules</h2>
  ${aeoModules}

  <div class="footer">
    <p>Generated by SitePulse AI • ${new Date().getFullYear()}</p>
  </div>
</body>
</html>`;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
