/* ── SitePulse AI — Shared Analysis Types ── */

export type Severity = 'critical' | 'warning' | 'info';

export interface SEOIssue {
  id: string;
  title: string;
  /** Human-readable finding grounded in the real page (e.g. "Title is 82 characters"). */
  description: string;
  severity: Severity;
  /** Whether the underlying rule passed. Passing checks are also returned so the UI can show wins. */
  passed: boolean;
  /** Points this check contributes toward the category score. */
  weight: number;
  fix: string;
  copyReadyExample: string;
}

export interface SEOResult {
  score: number;
  /** Only failing checks — what the user needs to act on. */
  issues: SEOIssue[];
  /** Every check, pass or fail, for a full breakdown. */
  checks: SEOIssue[];
}

export type AEOModuleType =
  | 'definition'
  | 'how-to'
  | 'faq'
  | 'faq-jsonld'
  | 'key-facts'
  | 'snippets';

/**
 * Where a module's content came from:
 *  - `ai`        → generated by an LLM, grounded in the real page content
 *  - `extracted` → built directly from content found on the page (real Q&As, real steps)
 *  - `scaffold`  → a labelled template to fill in, used only when the page has nothing to extract
 */
export type AEOModuleSource = 'ai' | 'extracted' | 'scaffold';

export interface AEOModule {
  id: string;
  type: AEOModuleType;
  title: string;
  content: string;
  source: AEOModuleSource;
  /** Optional context shown to the user, e.g. "Built from 4 questions found on your page." */
  note?: string;
}

export interface AEOResult {
  score: number;
  modules: AEOModule[];
  /** Failing/weak AEO checks with detail, mirrors SEOResult.checks. */
  checks: SEOIssue[];
}

export interface Recommendation {
  rank: number;
  title: string;
  description: string;
  priority: 'Quick-Win' | 'High-Impact' | 'Medium' | 'Low-Priority';
  category: 'seo' | 'aeo';
  fix: string;
  copyReadyExample: string;
  /** Estimated score points recovered by fixing this. Drives ranking. */
  impact: number;
}

export interface DraftContent {
  html: string;
  markdown: string;
  preview: string;
}

export interface Blueprint {
  samplePage: DraftContent;
  rolloutPlan: string;
}

export type SiteComplexity = 'EASY' | 'COMPLEX';

/** Lightweight, UI-facing summary of the raw signals we measured on the page. */
export interface PageSignals {
  finalUrl: string;
  httpStatus: number;
  /** How the HTML was retrieved: 'direct' | 'cloudflare' | 'firecrawl'. */
  fetchedVia: string;
  loadTimeMs: number;
  htmlKb: number;
  wordCount: number;
  title: string;
  description: string;
  h1Count: number;
  h2Count: number;
  imgCount: number;
  imgsMissingAlt: number;
  internalLinks: number;
  externalLinks: number;
  schemaTypes: string[];
  lang: string;
}

export interface AnalysisResult {
  id: string;
  url: string;
  analyzedAt: string;
  complexity: SiteComplexity;
  /** True when AEO/draft content was produced by an LLM rather than the deterministic engine. */
  aiEnhanced: boolean;
  signals: PageSignals;
  seo: SEOResult;
  aeo: AEOResult;
  recommendations: Recommendation[];
  draft?: DraftContent;
  blueprint?: Blueprint;
}
